name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck bats

      - name: Shellcheck
        run: make shellcheck

      - name: Bats
        run: make bats
